"""Initial migration

Revision ID: 40d9cb9fdf21
Revises:
Create Date: 2026-04-14 01:22:22.987273

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "40d9cb9fdf21"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("company", sa.String(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "PYTHON",
                "JAVA",
                "JAVASCRIPT",
                "TYPESCRIPT",
                "C",
                "GO",
                "RUST",
                "PHP",
                "RUBY",
                "SWIFT",
                "KOTLIN",
                "WEB",
                "MOBILE",
                "DATA",
                "AI",
                "CLOUD",
                "DEVOPS",
                "SECURITY",
                "GAME",
                "BLOCKCHAIN",
                "BACKEND",
                "FRONTEND",
                "FULLSTACK",
                "SRE",
                "QA",
                "DATA_SCIENCE",
                name="jobcategory",
            ),
            nullable=True,
        ),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("salary", sa.String(), nullable=True),
        sa.Column("job_type", sa.String(), nullable=True),
        sa.Column("skills", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("seniority", sa.String(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "status", sa.Enum("NEW", "PROCESSED", name="jobstatus"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("scraped_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("last_interaction", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_subscriptions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "PYTHON",
                "JAVA",
                "JAVASCRIPT",
                "TYPESCRIPT",
                "C",
                "GO",
                "RUST",
                "PHP",
                "RUBY",
                "SWIFT",
                "KOTLIN",
                "WEB",
                "MOBILE",
                "DATA",
                "AI",
                "CLOUD",
                "DEVOPS",
                "SECURITY",
                "GAME",
                "BLOCKCHAIN",
                "BACKEND",
                "FRONTEND",
                "FULLSTACK",
                "SRE",
                "QA",
                "DATA_SCIENCE",
                name="jobcategory",
            ),
            nullable=True,
        ),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("last_notified_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "category", "location", name="unique_user_subscription"
        ),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(), nullable=False),
        sa.Column("subscription_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(), nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["user_subscriptions.id"],
            name="fk_notifications_subscription_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "job_id", name="uq_user_job_notification"),
    )
    op.create_index(
        "idx_notifications_status_next_attempt",
        "notifications",
        ["status", "next_attempt_at"],
        unique=False,
    )
    op.create_index(
        "idx_notifications_user_id", "notifications", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_notifications_user_id", table_name="notifications")
    op.drop_index("idx_notifications_status_next_attempt", table_name="notifications")
    op.drop_table("notifications")
    op.drop_table("user_subscriptions")
    op.drop_table("users")
    op.drop_table("jobs")
    # ### end Alembic commands ###
