SEARCH_QUERIES = {
    "PYTHON": [
        "python developer",
        "python engineer",
        "django developer",
        "flask developer",
        "fastapi developer",
        "backend python",
        "python backend",
        "python api",
        "python automation",
        "python scripting",
        "async python",
        "ai python",
    ],
    "JAVA": [
        "java developer",
        "java engineer",
        "spring developer",
        "spring boot",
        "java backend",
        "backend java",
        "java microservices",
        "jvm developer",
        "hibernate",
        "java api",
    ],
    "JAVASCRIPT": [
        "javascript developer",
        "js developer",
        "frontend javascript",
        "node.js developer",
        "nodejs backend",
        "vanilla js",
        "es6 developer",
    ],
    "TYPESCRIPT": [
        "typescript developer",
        "ts developer",
        "typescript frontend",
        "node typescript",
        "nestjs developer",
        "angular typescript",
    ],
    "C": [
        "c developer",
        "embedded c",
        "low level programming",
        "systems programmer c",
        "firmware engineer c",
    ],
    "GO": [
        "golang developer",
        "go developer",
        "go backend",
        "microservices go",
        "cloud go",
        "backend golang",
    ],
    "RUST": [
        "rust developer",
        "rust engineer",
        "systems programming rust",
        "backend rust",
        "rust async",
        "webassembly rust",
    ],
    "PHP": [
        "php developer",
        "laravel developer",
        "symfony developer",
        "backend php",
        "wordpress developer",
        "magento developer",
    ],
    "RUBY": [
        "ruby developer",
        "ruby on rails",
        "rails developer",
        "backend ruby",
        "ror developer",
    ],
    "SWIFT": ["swift developer", "ios developer swift", "ios engineer", "mobile ios"],
    "KOTLIN": [
        "kotlin developer",
        "android kotlin",
        "android developer",
        "mobile android",
        "kotlin backend",
    ],
    "WEB": [
        "web developer",
        "full stack web",
        "frontend web",
        "backend web",
        "web engineer",
        "web applications",
    ],
    "MOBILE": [
        "mobile developer",
        "ios developer",
        "android developer",
        "react native developer",
        "flutter developer",
        "mobile engineer",
    ],
    "DATA": [
        "data engineer",
        "data analyst",
        "etl developer",
        "big data engineer",
        "data pipeline",
        "data warehouse",
        "spark engineer",
        "hadoop",
    ],
    "AI": [
        "ai engineer",
        "machine learning engineer",
        "ml engineer",
        "deep learning",
        "nlp engineer",
        "computer vision",
        "llm engineer",
        "ai developer",
    ],
    "CLOUD": [
        "cloud engineer",
        "aws engineer",
        "azure engineer",
        "gcp engineer",
        "cloud architect",
        "cloud infrastructure",
        "serverless",
        "cloud devops",
    ],
    "DEVOPS": [
        "devops engineer",
        "ci cd engineer",
        "platform engineer",
        "kubernetes engineer",
        "docker",
        "infrastructure as code",
        "terraform",
        "jenkins",
    ],
    "SECURITY": [
        "security engineer",
        "cybersecurity",
        "application security",
        "penetration tester",
        "pentester",
        "security analyst",
        "infosec",
        "network security",
    ],
    "GAME": [
        "game developer",
        "unity developer",
        "unreal engine",
        "game programmer",
        "c++ game dev",
        "game designer",
    ],
    "BLOCKCHAIN": [
        "blockchain developer",
        "web3 developer",
        "solidity developer",
        "smart contracts",
        "ethereum developer",
        "crypto engineer",
    ],
    "BACKEND": [
        "backend developer",
        "backend engineer",
        "api developer",
        "microservices",
        "server side developer",
        "rest api",
        "graphql backend",
    ],
    "FRONTEND": [
        "frontend developer",
        "frontend engineer",
        "react developer",
        "vue developer",
        "angular developer",
        "ui developer",
        "web frontend",
    ],
    "FULLSTACK": [
        "full stack developer",
        "fullstack engineer",
        "frontend backend developer",
        "end to end developer",
        "mern stack",
        "mean stack",
    ],
    "SRE": [
        "site reliability engineer",
        "sre engineer",
        "production engineer",
        "reliability engineer",
        "observability",
        "incident management",
    ],
    "QA": [
        "qa engineer",
        "test engineer",
        "automation tester",
        "qa automation",
        "software tester",
        "selenium",
        "manual tester",
    ],
    "DATA_SCIENCE": [
        "data scientist",
        "machine learning scientist",
        "data science",
        "predictive modeling",
        "statistics",
        "python data science",
        "r data science",
    ],
}

LOCATIONS = [
    "POLAND",
    "GERMANY",
    "IRELAND",
    "FRANCE",
    "SPAIN",
    "ITALY",
    "NETHERLANDS",
    "BELGIUM",
    "SWEDEN",
    "NORWAY",
    "DENMARK",
    "FINLAND",
    "SWITZERLAND",
    "AUSTRIA",
    "SLOVAKIA",
    "HUNGARY",
    "ROMANIA",
    "BULGARIA",
    "PORTUGAL",
    "GREECE",
    "UKRAINE",
    "LITHUANIA",
    "LATVIA",
    "ESTONIA",
    "CANADA",
    "MEXICO",
    "BRAZIL",
    "ARGENTINA",
    "CHILE",
    "COLOMBIA",
    "ISRAEL",
    "TURKEY",
    "UNITED_ARAB_EMIRATES",
    "SAUDI_ARABIA",
    "QATAR",
    "INDIA",
    "PAKISTAN",
    "BANGLADESH",
    "SINGAPORE",
    "INDONESIA",
    "MALAYSIA",
    "THAILAND",
    "VIETNAM",
    "PHILIPPINES",
    "CHINA",
    "JAPAN",
    "SOUTH_KOREA",
    "AUSTRALIA",
    "NEW_ZEALAND",
    "SOUTH_AFRICA",
    "EGYPT",
    "NIGERIA",
    "KENYA",
    "REMOTE",
]

INDEED_DOMAINS = {
    "POLAND": "https://pl.indeed.com",
    "GERMANY": "https://de.indeed.com",
    "IRELAND": "https://ie.indeed.com",
    "FRANCE": "https://fr.indeed.com",
    "SPAIN": "https://es.indeed.com",
    "ITALY": "https://it.indeed.com",
    "NETHERLANDS": "https://nl.indeed.com",
    "BELGIUM": "https://be.indeed.com",
    "SWEDEN": "https://se.indeed.com",
    "NORWAY": "https://no.indeed.com",
    "DENMARK": "https://dk.indeed.com",
    "FINLAND": "https://fi.indeed.com",
    "SWITZERLAND": "https://ch.indeed.com",
    "AUSTRIA": "https://at.indeed.com",
    "HUNGARY": "https://hu.indeed.com",
    "ROMANIA": "https://ro.indeed.com",
    "PORTUGAL": "https://pt.indeed.com",
    "GREECE": "https://gr.indeed.com",
    "TURKEY": "https://tr.indeed.com",
    "CANADA": "https://ca.indeed.com",
    "MEXICO": "https://mx.indeed.com",
    "BRAZIL": "https://br.indeed.com",
    "ARGENTINA": "https://ar.indeed.com",
    "CHILE": "https://cl.indeed.com",
    "COLOMBIA": "https://co.indeed.com",
    "PERU": "https://pe.indeed.com",
    "ISRAEL": "https://il.indeed.com",
    "QATAR": "https://qa.indeed.com",
    "INDIA": "https://in.indeed.com",
    "SINGAPORE": "https://sg.indeed.com",
    "MALAYSIA": "https://my.indeed.com",
    "INDONESIA": "https://id.indeed.com",
    "THAILAND": "https://th.indeed.com",
    "VIETNAM": "https://vn.indeed.com",
    "PHILIPPINES": "https://ph.indeed.com",
    "CHINA": "https://cn.indeed.com",
    "JAPAN": "https://jp.indeed.com",
    "AUSTRALIA": "https://au.indeed.com",
    "NIGERIA": "https://ng.indeed.com",
    "EGYPT": "https://eg.indeed.com",
    "KENYA": "https://ke.indeed.com",
}
